"""
AI Assignment 05 — Datasets
Two knowledge bases the agent queries: countries and products.
DO NOT MODIFY THIS FILE.
"""

COUNTRIES = [
    {"name": "United States", "capital": "Washington D.C.", "continent": "North America", "population": 331000000, "area_km2": 9833520, "gdp_billion": 25460, "gdp_per_capita": 76330, "official_language": "English", "currency": "USD"},
    {"name": "China", "capital": "Beijing", "continent": "Asia", "population": 1412000000, "area_km2": 9596960, "gdp_billion": 17960, "gdp_per_capita": 12720, "official_language": "Mandarin", "currency": "CNY"},
    {"name": "Japan", "capital": "Tokyo", "continent": "Asia", "population": 125700000, "area_km2": 377975, "gdp_billion": 4230, "gdp_per_capita": 33650, "official_language": "Japanese", "currency": "JPY"},
    {"name": "Germany", "capital": "Berlin", "continent": "Europe", "population": 83200000, "area_km2": 357022, "gdp_billion": 4070, "gdp_per_capita": 48920, "official_language": "German", "currency": "EUR"},
    {"name": "India", "capital": "New Delhi", "continent": "Asia", "population": 1408000000, "area_km2": 3287263, "gdp_billion": 3390, "gdp_per_capita": 2410, "official_language": "Hindi", "currency": "INR"},
    {"name": "United Kingdom", "capital": "London", "continent": "Europe", "population": 67300000, "area_km2": 243610, "gdp_billion": 3070, "gdp_per_capita": 45600, "official_language": "English", "currency": "GBP"},
    {"name": "France", "capital": "Paris", "continent": "Europe", "population": 67750000, "area_km2": 551695, "gdp_billion": 2780, "gdp_per_capita": 41040, "official_language": "French", "currency": "EUR"},
    {"name": "Canada", "capital": "Ottawa", "continent": "North America", "population": 38900000, "area_km2": 9984670, "gdp_billion": 2140, "gdp_per_capita": 55010, "official_language": "English", "currency": "CAD"},
    {"name": "Italy", "capital": "Rome", "continent": "Europe", "population": 58900000, "area_km2": 301340, "gdp_billion": 2010, "gdp_per_capita": 34100, "official_language": "Italian", "currency": "EUR"},
    {"name": "Brazil", "capital": "Brasilia", "continent": "South America", "population": 214000000, "area_km2": 8515767, "gdp_billion": 1920, "gdp_per_capita": 8970, "official_language": "Portuguese", "currency": "BRL"},
    {"name": "Russia", "capital": "Moscow", "continent": "Europe", "population": 144000000, "area_km2": 17098242, "gdp_billion": 1780, "gdp_per_capita": 12360, "official_language": "Russian", "currency": "RUB"},
    {"name": "South Korea", "capital": "Seoul", "continent": "Asia", "population": 51700000, "area_km2": 100210, "gdp_billion": 1670, "gdp_per_capita": 32250, "official_language": "Korean", "currency": "KRW"},
    {"name": "Australia", "capital": "Canberra", "continent": "Oceania", "population": 26000000, "area_km2": 7692024, "gdp_billion": 1680, "gdp_per_capita": 64600, "official_language": "English", "currency": "AUD"},
    {"name": "Mexico", "capital": "Mexico City", "continent": "North America", "population": 128900000, "area_km2": 1964375, "gdp_billion": 1320, "gdp_per_capita": 10240, "official_language": "Spanish", "currency": "MXN"},
    {"name": "Spain", "capital": "Madrid", "continent": "Europe", "population": 47420000, "area_km2": 505992, "gdp_billion": 1400, "gdp_per_capita": 29520, "official_language": "Spanish", "currency": "EUR"},
    {"name": "Indonesia", "capital": "Jakarta", "continent": "Asia", "population": 275500000, "area_km2": 1904569, "gdp_billion": 1320, "gdp_per_capita": 4790, "official_language": "Indonesian", "currency": "IDR"},
    {"name": "Netherlands", "capital": "Amsterdam", "continent": "Europe", "population": 17530000, "area_km2": 41543, "gdp_billion": 1010, "gdp_per_capita": 57590, "official_language": "Dutch", "currency": "EUR"},
    {"name": "Saudi Arabia", "capital": "Riyadh", "continent": "Asia", "population": 36400000, "area_km2": 2149690, "gdp_billion": 1110, "gdp_per_capita": 30490, "official_language": "Arabic", "currency": "SAR"},
    {"name": "Turkey", "capital": "Ankara", "continent": "Asia", "population": 85280000, "area_km2": 783562, "gdp_billion": 906, "gdp_per_capita": 10620, "official_language": "Turkish", "currency": "TRY"},
    {"name": "Switzerland", "capital": "Bern", "continent": "Europe", "population": 8770000, "area_km2": 41285, "gdp_billion": 818, "gdp_per_capita": 93260, "official_language": "German", "currency": "CHF"},
    {"name": "Poland", "capital": "Warsaw", "continent": "Europe", "population": 37750000, "area_km2": 312696, "gdp_billion": 690, "gdp_per_capita": 18280, "official_language": "Polish", "currency": "PLN"},
    {"name": "Sweden", "capital": "Stockholm", "continent": "Europe", "population": 10420000, "area_km2": 450295, "gdp_billion": 586, "gdp_per_capita": 56240, "official_language": "Swedish", "currency": "SEK"},
    {"name": "Argentina", "capital": "Buenos Aires", "continent": "South America", "population": 45810000, "area_km2": 2780400, "gdp_billion": 632, "gdp_per_capita": 13800, "official_language": "Spanish", "currency": "ARS"},
    {"name": "Norway", "capital": "Oslo", "continent": "Europe", "population": 5460000, "area_km2": 323802, "gdp_billion": 482, "gdp_per_capita": 88290, "official_language": "Norwegian", "currency": "NOK"},
    {"name": "Nigeria", "capital": "Abuja", "continent": "Africa", "population": 218500000, "area_km2": 923768, "gdp_billion": 477, "gdp_per_capita": 2180, "official_language": "English", "currency": "NGN"},
    {"name": "Austria", "capital": "Vienna", "continent": "Europe", "population": 9100000, "area_km2": 83871, "gdp_billion": 471, "gdp_per_capita": 51750, "official_language": "German", "currency": "EUR"},
    {"name": "South Africa", "capital": "Pretoria", "continent": "Africa", "population": 60600000, "area_km2": 1219090, "gdp_billion": 405, "gdp_per_capita": 6680, "official_language": "English", "currency": "ZAR"},
    {"name": "Egypt", "capital": "Cairo", "continent": "Africa", "population": 104300000, "area_km2": 1001450, "gdp_billion": 476, "gdp_per_capita": 4560, "official_language": "Arabic", "currency": "EGP"},
    {"name": "Denmark", "capital": "Copenhagen", "continent": "Europe", "population": 5870000, "area_km2": 42924, "gdp_billion": 395, "gdp_per_capita": 67320, "official_language": "Danish", "currency": "DKK"},
    {"name": "Singapore", "capital": "Singapore", "continent": "Asia", "population": 5640000, "area_km2": 728, "gdp_billion": 397, "gdp_per_capita": 72790, "official_language": "English", "currency": "SGD"},
    {"name": "Malaysia", "capital": "Kuala Lumpur", "continent": "Asia", "population": 33200000, "area_km2": 330803, "gdp_billion": 407, "gdp_per_capita": 12260, "official_language": "Malay", "currency": "MYR"},
    {"name": "Pakistan", "capital": "Islamabad", "continent": "Asia", "population": 231000000, "area_km2": 881913, "gdp_billion": 376, "gdp_per_capita": 1630, "official_language": "Urdu", "currency": "PKR"},
    {"name": "Colombia", "capital": "Bogota", "continent": "South America", "population": 51870000, "area_km2": 1141748, "gdp_billion": 343, "gdp_per_capita": 6610, "official_language": "Spanish", "currency": "COP"},
    {"name": "Chile", "capital": "Santiago", "continent": "South America", "population": 19490000, "area_km2": 756102, "gdp_billion": 301, "gdp_per_capita": 15440, "official_language": "Spanish", "currency": "CLP"},
    {"name": "Finland", "capital": "Helsinki", "continent": "Europe", "population": 5540000, "area_km2": 338424, "gdp_billion": 282, "gdp_per_capita": 50910, "official_language": "Finnish", "currency": "EUR"},
    {"name": "Vietnam", "capital": "Hanoi", "continent": "Asia", "population": 99460000, "area_km2": 331212, "gdp_billion": 409, "gdp_per_capita": 4110, "official_language": "Vietnamese", "currency": "VND"},
    {"name": "Bangladesh", "capital": "Dhaka", "continent": "Asia", "population": 169400000, "area_km2": 147570, "gdp_billion": 460, "gdp_per_capita": 2720, "official_language": "Bengali", "currency": "BDT"},
    {"name": "Portugal", "capital": "Lisbon", "continent": "Europe", "population": 10350000, "area_km2": 92212, "gdp_billion": 253, "gdp_per_capita": 24450, "official_language": "Portuguese", "currency": "EUR"},
    {"name": "Czech Republic", "capital": "Prague", "continent": "Europe", "population": 10510000, "area_km2": 78866, "gdp_billion": 291, "gdp_per_capita": 27690, "official_language": "Czech", "currency": "CZK"},
    {"name": "Romania", "capital": "Bucharest", "continent": "Europe", "population": 19120000, "area_km2": 238397, "gdp_billion": 301, "gdp_per_capita": 15740, "official_language": "Romanian", "currency": "RON"},
    {"name": "New Zealand", "capital": "Wellington", "continent": "Oceania", "population": 5120000, "area_km2": 268021, "gdp_billion": 247, "gdp_per_capita": 48240, "official_language": "English", "currency": "NZD"},
    {"name": "Peru", "capital": "Lima", "continent": "South America", "population": 33720000, "area_km2": 1285216, "gdp_billion": 242, "gdp_per_capita": 7180, "official_language": "Spanish", "currency": "PEN"},
    {"name": "Kenya", "capital": "Nairobi", "continent": "Africa", "population": 54000000, "area_km2": 580367, "gdp_billion": 113, "gdp_per_capita": 2090, "official_language": "English", "currency": "KES"},
    {"name": "Ethiopia", "capital": "Addis Ababa", "continent": "Africa", "population": 120300000, "area_km2": 1104300, "gdp_billion": 126, "gdp_per_capita": 1050, "official_language": "Amharic", "currency": "ETB"},
    {"name": "Luxembourg", "capital": "Luxembourg City", "continent": "Europe", "population": 654000, "area_km2": 2586, "gdp_billion": 85, "gdp_per_capita": 129810, "official_language": "French", "currency": "EUR"},
    {"name": "Thailand", "capital": "Bangkok", "continent": "Asia", "population": 71800000, "area_km2": 513120, "gdp_billion": 536, "gdp_per_capita": 7470, "official_language": "Thai", "currency": "THB"},
    {"name": "Philippines", "capital": "Manila", "continent": "Asia", "population": 113900000, "area_km2": 300000, "gdp_billion": 404, "gdp_per_capita": 3550, "official_language": "Filipino", "currency": "PHP"},
    {"name": "Ghana", "capital": "Accra", "continent": "Africa", "population": 33500000, "area_km2": 238533, "gdp_billion": 77, "gdp_per_capita": 2300, "official_language": "English", "currency": "GHS"},
    {"name": "Ireland", "capital": "Dublin", "continent": "Europe", "population": 5060000, "area_km2": 70273, "gdp_billion": 529, "gdp_per_capita": 104530, "official_language": "English", "currency": "EUR"},
    {"name": "Morocco", "capital": "Rabat", "continent": "Africa", "population": 37080000, "area_km2": 446550, "gdp_billion": 134, "gdp_per_capita": 3610, "official_language": "Arabic", "currency": "MAD"},
]

PRODUCTS = [
    {"name": "UltraPhone Pro", "category": "Electronics", "price": 1199.99, "revenue": 850000, "origin_country": "United States", "rating": 4.7, "in_stock": True},
    {"name": "SmartWatch X3", "category": "Electronics", "price": 349.99, "revenue": 420000, "origin_country": "South Korea", "rating": 4.3, "in_stock": True},
    {"name": "NoiseFree Buds", "category": "Electronics", "price": 199.99, "revenue": 610000, "origin_country": "Japan", "rating": 4.5, "in_stock": True},
    {"name": "TurboLaptop 16", "category": "Electronics", "price": 1899.99, "revenue": 1200000, "origin_country": "United States", "rating": 4.8, "in_stock": False},
    {"name": "GameStation 6", "category": "Electronics", "price": 499.99, "revenue": 950000, "origin_country": "Japan", "rating": 4.6, "in_stock": True},
    {"name": "CloudCam Mini", "category": "Electronics", "price": 79.99, "revenue": 180000, "origin_country": "China", "rating": 3.9, "in_stock": True},
    {"name": "SolarPanel Kit", "category": "Energy", "price": 899.99, "revenue": 320000, "origin_country": "Germany", "rating": 4.4, "in_stock": True},
    {"name": "WindTurbine Home", "category": "Energy", "price": 3500.00, "revenue": 150000, "origin_country": "Denmark", "rating": 4.1, "in_stock": False},
    {"name": "PowerBank Ultra", "category": "Energy", "price": 59.99, "revenue": 480000, "origin_country": "China", "rating": 4.0, "in_stock": True},
    {"name": "EcoCharger V2", "category": "Energy", "price": 44.99, "revenue": 290000, "origin_country": "Sweden", "rating": 4.2, "in_stock": True},
    {"name": "OrganicTea Set", "category": "Food", "price": 24.99, "revenue": 95000, "origin_country": "India", "rating": 4.6, "in_stock": True},
    {"name": "GourmetCoffee Beans", "category": "Food", "price": 18.99, "revenue": 210000, "origin_country": "Colombia", "rating": 4.8, "in_stock": True},
    {"name": "SuperProtein Bar", "category": "Food", "price": 3.49, "revenue": 870000, "origin_country": "United States", "rating": 4.1, "in_stock": True},
    {"name": "SpiceBox World", "category": "Food", "price": 34.99, "revenue": 140000, "origin_country": "India", "rating": 4.3, "in_stock": True},
    {"name": "HealthySnack Mix", "category": "Food", "price": 8.99, "revenue": 350000, "origin_country": "Australia", "rating": 4.0, "in_stock": True},
    {"name": "RunnerShoe Elite", "category": "Sports", "price": 189.99, "revenue": 760000, "origin_country": "Germany", "rating": 4.7, "in_stock": True},
    {"name": "YogaMat Pro", "category": "Sports", "price": 49.99, "revenue": 230000, "origin_country": "India", "rating": 4.4, "in_stock": True},
    {"name": "CycleHelmet Air", "category": "Sports", "price": 129.99, "revenue": 170000, "origin_country": "Italy", "rating": 4.5, "in_stock": True},
    {"name": "FitTracker Band", "category": "Sports", "price": 69.99, "revenue": 510000, "origin_country": "China", "rating": 4.2, "in_stock": True},
    {"name": "TennisPro Racket", "category": "Sports", "price": 249.99, "revenue": 190000, "origin_country": "France", "rating": 4.6, "in_stock": False},
    {"name": "MountainBike X7", "category": "Sports", "price": 1599.99, "revenue": 430000, "origin_country": "Canada", "rating": 4.8, "in_stock": True},
    {"name": "NovelMaster E-Reader", "category": "Books", "price": 139.99, "revenue": 380000, "origin_country": "United States", "rating": 4.3, "in_stock": True},
    {"name": "CodeBook Python", "category": "Books", "price": 49.99, "revenue": 120000, "origin_country": "United Kingdom", "rating": 4.7, "in_stock": True},
    {"name": "WorldAtlas 2025", "category": "Books", "price": 29.99, "revenue": 85000, "origin_country": "Germany", "rating": 4.0, "in_stock": True},
    {"name": "CookBook Fusion", "category": "Books", "price": 24.99, "revenue": 160000, "origin_country": "France", "rating": 4.5, "in_stock": True},
    {"name": "SkinCare Luxe Set", "category": "Beauty", "price": 89.99, "revenue": 540000, "origin_country": "France", "rating": 4.6, "in_stock": True},
    {"name": "HairOil Natural", "category": "Beauty", "price": 14.99, "revenue": 290000, "origin_country": "India", "rating": 4.2, "in_stock": True},
    {"name": "Perfume Essence", "category": "Beauty", "price": 159.99, "revenue": 410000, "origin_country": "France", "rating": 4.8, "in_stock": True},
    {"name": "FaceMask Pack", "category": "Beauty", "price": 19.99, "revenue": 310000, "origin_country": "South Korea", "rating": 4.4, "in_stock": True},
    {"name": "SmartHome Hub", "category": "Electronics", "price": 149.99, "revenue": 330000, "origin_country": "United States", "rating": 4.1, "in_stock": True},
    {"name": "DroneFlyer X2", "category": "Electronics", "price": 799.99, "revenue": 270000, "origin_country": "China", "rating": 4.3, "in_stock": True},
    {"name": "TableSpeaker Mini", "category": "Electronics", "price": 59.99, "revenue": 450000, "origin_country": "Sweden", "rating": 4.4, "in_stock": True},
    {"name": "WaterBottle Smart", "category": "Sports", "price": 34.99, "revenue": 200000, "origin_country": "Australia", "rating": 4.1, "in_stock": True},
    {"name": "BackPack Trek", "category": "Sports", "price": 119.99, "revenue": 340000, "origin_country": "Switzerland", "rating": 4.7, "in_stock": True},
    {"name": "SleepMask Silk", "category": "Beauty", "price": 22.99, "revenue": 180000, "origin_country": "China", "rating": 4.0, "in_stock": True},
    {"name": "EssentialOil Kit", "category": "Beauty", "price": 39.99, "revenue": 260000, "origin_country": "Australia", "rating": 4.3, "in_stock": True},
    {"name": "BatteryPack Mega", "category": "Energy", "price": 129.99, "revenue": 190000, "origin_country": "Japan", "rating": 4.5, "in_stock": True},
    {"name": "SolarLantern", "category": "Energy", "price": 29.99, "revenue": 110000, "origin_country": "India", "rating": 3.8, "in_stock": True},
    {"name": "ChildrenBook ABC", "category": "Books", "price": 12.99, "revenue": 240000, "origin_country": "United Kingdom", "rating": 4.6, "in_stock": True},
    {"name": "Journal Premium", "category": "Books", "price": 19.99, "revenue": 170000, "origin_country": "Italy", "rating": 4.2, "in_stock": True},
]


DATASETS = {
    "countries": COUNTRIES,
    "products": PRODUCTS,
}
